version: '3.7'

services:
  db:
    container_name: db_desafio
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=desafio
      - POSTGRES_PASSWORD=desafio
      - POSTGRES_DB=desafio_dock
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  desafio-api:
    build:
      context: ./api
    image: desafio-api
    ports:
      - "8080:8080"
    environment:
      - api.database.name=desafio_dock
      - api.database.host=db
      - api.database.username=desafio
      - api.database.password=desafio
    depends_on:
      - db

volumes:
  db_data: