server:
  port: ${PORT:8080}

api:
  database:
    name: desafio_dock
    host: 127.0.0.1
    port: 5432
    username: desafio
    password: desafio

spring:
  application:
    name: deafio-dock-api
  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/desafio_dock?schema=public
    url: r2dbc:postgresql://${api.database.host}:${api.database.port}/${api.database.name}
    password: ${api.database.password}
    username: ${api.database.username}

  liquibase:
    enabled: true
    change-log: classpath:db/master.yaml
    contexts: local, dev, prd
    url: jdbc:postgresql://${api.database.host}:${api.database.port}/${api.database.name}
#    url: jdbc:postgresql://localhost:5432/desafio_dock?schema=public
    user: ${api.database.username}
    password: ${api.database.password}

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

